---
name: Markdownlint

on:
  pull_request:
    branches: [ main ]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            content/*.md
            content/**/*.md